### ISSUE TITLE
功能扩展

### ISSUE THREAD

**Issue by tangqiao42** [yhaolpz/FloatWindow#11]

**Comment by tangqiao42** [comment]
![image](https://user-images.githubusercontent.com/15665193/34485222-571e60a6-f004-11e7-9ffe-00ca592799d3.png)

**Comment by tangqiao42** [comment]
要是能实现上面三四点就完美了，实在不行至少能支持可以左滑或者右滑切换到半隐藏状态就好，或者在左右两边停留几秒时切换到两个半透明状态就好了，类似应用市场的悬浮球
![image](https://user-images.githubusercontent.com/15665193/34485265-af2f9cf6-f004-11e7-8d08-623e2587f541.png)

**Comment by yhaolpz** [comment]
@tangqiao42 非常不错的功能！后面有时间集成进去，感谢提出！

**Comment by tangqiao42** [comment]
嗯，    目前我也开发了一套应用市场的sdk  其中悬浮球功能很类似  兼容性多少存在点问题 项目需求  我看到功能很相似，如果能加上相应功能就厉害了
