### ISSUE TITLE
权限申请回调

### ISSUE THREAD

**Issue by hzl123456** [yhaolpz/FloatWindow#16]
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == 756232212) {
            if (PermissionUtil.hasPermissionOnActivityResult(this)) {
                mPermissionListener.onSuccess();
            } else {
               //这里应该是 mPermissionListener.onFail();
                mPermissionListener.onSuccess();
            }
        }
        finish();
    }
代码中申请悬浮窗权限的回调错误，导致的直接问题是在申请悬浮窗权限的时候，用户选择了拒绝。应用崩溃

**Comment by yhaolpz** [comment]
@hzl123456  非常感谢你！
