### ISSUE TITLE
（忽略）宽高不能wrap_content

### ISSUE THREAD

**Issue by lanshifu** [yhaolpz/FloatWindow#17]
看了下代码，宽高通过setWidth   setHeight  传固定的。
如果我的悬浮窗是一个textview，希望宽高可以根据textview内容自适应，能否添加支持呢

**Comment by yhaolpz** [comment]
@lanshifu  不调用 setWidth  setHeight 方法不能实现自适应吗？

**Comment by lanshifu** [comment]
直接看demo设置了宽高，没看清楚说明，默认是wrap_content。
这个库很强大，以后可以不用写windowmanager申请权限了，小星星奉上

**Comment by yhaolpz** [comment]
@lanshifu  谢谢~
