### ISSUE TITLE
设置按钮 点击就有有问题

### ISSUE THREAD

**Issue by yishangfei** [yhaolpz/FloatWindow#19]
如果是初始化的时候加载是没有问题   可以设置成按钮点击事件   就必须退到桌面 然后重进才会开启

**Comment by lanshifu** [comment]
对，只有oncreate 去设置才会显示，点击按钮去show不显示，要退到后台重新进走了onResume才会显示。
在service 中也是这样。

**Comment by yishangfei** [comment]
那有何解决办法吗 @lanshifu

**Comment by yhaolpz** [comment]
#44
