### ISSUE TITLE
小米手机能够直接申请权限吗

### ISSUE THREAD

**Issue by willBars** [yhaolpz/FloatWindow#2]
你好:
   博主:对于申请权限这块,小米手机就是个奇葩,需要用户手动去申请,但是其用户体验不好,有没能只能跳过申请权限的呢,特别是对于小米手机!

**Comment by yhaolpz** [comment]
我封装的是 7.1 以下所有机型都跳过申请权限，跳不跳过权限申请由 Andorid 版本决定的，如果你只需要跳过权限申请的方法，可以下载下来改改。

**Comment by yhaolpz** [comment]
@willBars  v1.0.3 已增加其他方案的灵活选择。

**Comment by willBars** [comment]
demo已经下载下来看了!非常不错! 这个floatWindow是固定的,怎么样才能是悬浮移动的呢?

**Comment by willBars** [comment]
期待

**Comment by yhaolpz** [comment]
@willBars  v1.0.6 支持悬浮窗移动了。
