### ISSUE TITLE
小米权限如何重新获取

### ISSUE THREAD

**Issue by zhongcg** [yhaolpz/FloatWindow#21]
第一次获取权限时用户未授权悬浮窗权限，第二次进入页面如何重新获取权限。

    @Override
    public void show() {
        if (once) {
            mFloatView.init();
            once = false;
            isShow = true;
        } else {
            if (isShow) return;
            getView().setVisibility(View.VISIBLE);
            isShow = true;
        }
    }
第一次进来时，未获取到权限，isShow = true。 第二次进页面，如何重新获取权限并初始化mFloatView

**Comment by yhaolpz** [comment]
v1.0.9添加权限申请结果回调，可处理这种情况。
