### ISSUE TITLE
非常棒！

### ISSUE THREAD

**Issue by ChestnutPlus** [yhaolpz/FloatWindow#22]
建议加上这几个功能：
1. 设置悬浮球左右贴边的Margin。
2. 加入记录悬浮球的位置，当用户重新改变了悬浮球的位置，那么下一次在新的位置出现。
以上我都实现了，建议楼主加上去。

**Comment by yhaolpz** [comment]
v1.0.9已支持。

**Comment by yhaolpz** [comment]
v1.0.9已支持。
