### ISSUE TITLE
消息情况

### ISSUE THREAD

**Issue by ujffdi** [yhaolpz/FloatWindow#23]
假设main入口的activity为A。依次有A,B,C，A跳往B、在B创建悬浮窗可以显示一会然后消失，跳到C的时候情况一样。但在A创建则一切正常

**Comment by ujffdi** [comment]
标题打错字emmm

**Comment by yhaolpz** [comment]
@ujffdi  在 application 中创建

**Comment by zzm123456** [comment]
@yhaolpz 有些需求需要在activity创建，要咋办。。

**Comment by xuyingke** [comment]
没看懂……@ujffdi

**Comment by yhaolpz** [comment]
#44
