### ISSUE TITLE
拖动的时候回触发点击事件

### ISSUE THREAD

**Issue by liunewshine** [yhaolpz/FloatWindow#26]
怎样拖动的时候不触发点击事件？

**Comment by lihanguang** [comment]
感觉用GestureDetector封装一下触摸事件就可以了吧

**Comment by xuyingke** [comment]
正在写这部分代码~  中午的时候pull request ~

**Comment by lanlan-yang** [comment]
没有好啊，还是有这个问题

**Comment by xuyingke** [comment]
你是在BaseApplication 中为imageview设置点击事件吗？


我这里是没有问题的。之前是：拖动时高几率触发点击事件，我改动后区分了点击和拖动。




原始邮件
发件人:lanlan-yangnotifications@github.com
收件人:yhaolpz/FloatWindowFloatWindow@noreply.github.com
抄送:xuyingkexuyingke@huxiu.com; Commentcomment@noreply.github.com
发送时间:2018年4月20日(周五) 16:26
主题:Re: [yhaolpz/FloatWindow] 拖动的时候回触发点击事件 (#26)


没有好啊，还是有这个问题

**Comment by xuyingke** [comment]
![floatwindow](https://user-images.githubusercontent.com/14024173/39613683-9d7aaba8-4f9b-11e8-8ae6-92b3db2ff201.png)

**Comment by yhaolpz** [comment]
v1.0.9已添加。
