### ISSUE TITLE
在service里new一个MyFloatWindow，然后调show方法无法显示

### ISSUE THREAD

**Issue by androrz** [yhaolpz/FloatWindow#3]
我想在service里弹出悬浮窗，就像这样，new了一个实例，然后去show，结果显示不了
mFloatWindow = new MyFloatWindow(this);
mFloatWindow.show();
必须要想demo那样，registerActivityLifecycleCallbacks监听，然后在回调里去show才行吗

**Comment by yhaolpz** [comment]
＠androrz MyFloatWindow　是针对我的 demo 案例的对 FixedFloatWindow 的封装工具，只适用于我的案例啊，你应该用本库的 FixedFloatWindow 类．
