### ISSUE TITLE
悬浮窗View的事件监听，不影响您的框架的前提下如何实现？

### ISSUE THREAD

**Issue by hhhaiai** [yhaolpz/FloatWindow#30]
RT

**Comment by xuyingke** [comment]
直接对你设置进去的view设置监听事件，但是事件时有问题的。我pull request 了，但是还没合并~~~  @hhhaiai

**Comment by yhaolpz** [comment]
v1.0.9已更新，非常感谢@xuyingke对本库的帮助。
