### ISSUE TITLE
不显示悬浮窗，第二次进入应用才显示。

### ISSUE THREAD

**Issue by pencilso** [yhaolpz/FloatWindow#44]
FloatWindow
                .with(getApplicationContext())
                .setView(imageView)
                .setDesktopShow(true)                //默认 false
                .build();

在界面上到按钮点击后，执行上述代码，然后屏幕上并没有显示悬浮窗，然后我点击home按键，回到桌面，也没有显示，然后我再次进入app到时候，这时候却出现了悬浮窗。
测试环境： 一加5T Android 8.1

**Comment by chenfd99** [comment]
我也发现了这个问题

**Comment by chenfd99** [comment]
是这样的 如果在onCreate里初始化界面呢 悬浮窗就会显示   当在按钮的setOnClickListener 里初始化呢 就需要第二次进入才会显示悬浮窗

**Comment by pencilso** [comment]
好神奇

**Comment by chenfd99** [comment]
我今天闲来有空 研究了一下怎么按需求创建并显示悬浮窗
首先把库下载下来
修改FloatWindow类里的build方法  ,使其返回IFloatWindow类型, 再在build方法的后面 增加一行
return floatWindowImpl;
代码如下:
```
//这里本来是void类型  修改成IFloatWindow
public IFloatWindow build() {
            if (mFloatWindowMap == null) {
                mFloatWindowMap = new HashMap<>();
            }
            if (mFloatWindowMap.containsKey(mTag)) {
                throw new IllegalArgumentException("FloatWindow of this tag has been added, Please set a new tag for the new FloatWindow");
            }
            if (mView == null && mLayoutId == 0) {
                throw new IllegalArgumentException("View has not been set!");
            }
            if (mView == null) {
                mView = Util.inflate(mApplicationContext, mLayoutId);
            }
            IFloatWindow floatWindowImpl = new IFloatWindowImpl(this);
            mFloatWindowMap.put(mTag, floatWindowImpl);
            return floatWindowImpl;  //这里返回floatWindowImpl
        }
```
调用的时候  在build后面调用一次 show()方法即可 ,如下:
``` 
FloatWindow.with(MyApplication.getContext())
                .setView(view)
                .setDesktopShow(true)
                .build()
                .show()
```

**Comment by yhaolpz** [comment]
悬浮窗的设计初衷用于多 Activity 显示，我当初的思路是在 Application 中创建这个“全局视图”，所以代码逻辑是在 Activity Resumed 时才会处理悬浮窗的显示与否，但是这一全局视图可能在某个Activity 中才会设置开启，针对这种情况可以在初始化后紧接着调用
`FloatWindow.get().show();`
即可。
