### ISSUE TITLE
可否添加一个位置监听

### ISSUE THREAD

**Issue by leielyq** [yhaolpz/FloatWindow#45]
自己添加setOnTouchListener()的话会覆盖手势响应

var con = layoutInflater.inflate(R.layout.view_alert, null)

        var alert = FloatWindow
                .with(getApplicationContext())
                .setView(con)
                .setDesktopShow(true)
                .build()

        con.setOnTouchListener { con, event ->
            Log.d("ceshi", event.x.toString())
            false
        }

**Comment by yhaolpz** [comment]
v1.0.9已添加。
