### ISSUE TITLE
小米5 MIUI9 7.12.14 Andorid 7.0 报错

### ISSUE THREAD

**Issue by yale8848** [yhaolpz/FloatWindow#6]
show = mTN.getClass().getMethod("show");
找不到这个方法，有空了麻烦看看，谢谢了

**Comment by yhaolpz** [comment]
@yale8848 可以测下现在的版本还有没有问题~

**Comment by yale8848** [comment]
现在可以了，谢谢了；
但是还是要申请权限，我想着能最好能实现在应用内不需要申请权限；

**Comment by yhaolpz** [comment]
小米的适配可以看看源码的miui类，解释了为什么小米需要申请权限～

**Comment by yale8848** [comment]
嗯 好的，谢谢啦

**Comment by yale8848** [comment]
小米5 MIUI9 7.12.14 Andorid 7.0
我发现喜马拉雅底部中间的播放按钮是悬浮的，但是它没有申请权限，不知道是如何实现

**Comment by yhaolpz** [comment]
@yale8848 应该是对各种机型比较复杂的判断，后面有时间我也试试~

**Comment by yale8848** [comment]
估计是吧，谢谢了
